"""add models

Revision ID: caa7973efa35
Revises: 
Create Date: 2024-03-12 12:33:14.370211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caa7973efa35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.Column('practice', sa.Integer(), nullable=True),
    sa.Column('home_work', sa.Integer(), nullable=True),
    sa.Column('project_portfolio', sa.Integer(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('sub_title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_id'), 'course', ['id'], unique=False)
    op.create_table('for_who',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_for_who_id'), 'for_who', ['id'], unique=False)
    op.create_table('learn_format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('ONLINE', 'OFFLINE', 'INDIVIDUAL', 'INDIVIDUAL_ONLINE', 'GROUP_ONLINE', 'INDIVIDUAL_OFFLINE', 'GROUP_OFFLINE', name='grouptypeenum'), nullable=True),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('desc_2', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learn_format_id'), 'learn_format', ['id'], unique=False)
    op.create_table('start_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('when_start', sa.String(), nullable=False),
    sa.Column('group_lang', sa.String(), nullable=True),
    sa.Column('time_start', sa.String(), nullable=True),
    sa.Column('time_end', sa.String(), nullable=True),
    sa.Column('weeks', sa.String(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_start_group_id'), 'start_group', ['id'], unique=False)
    op.create_table('student_work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('image_name', sa.String(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_work_id'), 'student_work', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_work_id'), table_name='student_work')
    op.drop_table('student_work')
    op.drop_index(op.f('ix_start_group_id'), table_name='start_group')
    op.drop_table('start_group')
    op.drop_index(op.f('ix_learn_format_id'), table_name='learn_format')
    op.drop_table('learn_format')
    op.drop_index(op.f('ix_for_who_id'), table_name='for_who')
    op.drop_table('for_who')
    op.drop_index(op.f('ix_course_id'), table_name='course')
    op.drop_table('course')
    # ### end Alembic commands ###
